# Generated by Django 3.2.16 on 2023-03-25 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='e.g: "+998912345678"', regex='^\\+?998[\\d]{9}$')]),
        ),
    ]
