# Generated by Django 3.2.16 on 2023-03-26 04:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
