# Generated by Django 3.2.16 on 2023-03-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_lecture_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='youtube',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
